services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php_container
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
